package com.example.ai.model

enum class AICapability {
    BACKGROUND_REMOVAL,
    OBJECT_DETECTION,
    OBJECT_REMOVAL,
    UPSCALE,
    ENHANCEMENT,
    RESTYLE,
    VIDEO_OBJECT_DETECTION,
    VIDEO_OBJECT_TRACKING,
    SMART_CUT,
    AUTO_CAPTIONS,
    VIDEO_ENHANCEMENT,
    SMART_REFRAME,
    GENERATIVE_FILL,
    OBJECT_REPLACEMENT,
    IMAGE_TO_IMAGE,
    IMAGE_TO_VIDEO,
    VIDEO_TO_VIDEO,
    VIDEO_EXTENSION
}

enum class AICapabilityStatus {
    AVAILABLE,
    PROCESSING,
    REQUIRES_CLOUD,
    REQUIRES_PROVIDER,
    REQUIRES_MODEL,
    DEVICE_NOT_SUPPORTED,
    UNAVAILABLE,
    FAILED,
    CANCELLED
}
